name: fetch current courses

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  FetchCurrent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        department: [0,1,2]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Connect to Cloudflare warp
      run: bash <(curl -fsSL git.io/warp.sh) proxy
    - name: Install npm packages
      run: npm install
    - name: fetch course data
      run: node fetchCourse.js ${{ matrix.department }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.department }}
        path: ./dist/
        retention-days: 2
  FetchSyllabus:
    needs: FetchCurrent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        department: [0,1,2]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.department }}
        path: ./dist/
    - name: Setup Node
      uses: actions/setup-node@v2-beta
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install npm packages
      run: npm install
    - name: fetch course data
      run: node fetchSyllabus.js ${{ matrix.department }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.department }}
        path: ./dist/
        retention-days: 2
  Deploy:
    needs: [FetchCurrent, FetchSyllabus]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: 0
        path: ./dist/
    - uses: actions/download-artifact@v2
      with:
        name: 1
        path: ./dist/
    - uses: actions/download-artifact@v2
      with:
        name: 2
        path: ./dist/
    - name: Show All years
      run: ls -R
      working-directory: ./dist/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        keep_files: true
