name: fetch current departments

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  FetchDepartment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - name: Install npm packages
      run: npm install
    - name: Fetch department data
      run: node fetchDepartment.js
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        keep_files: true
