name: fetch current mprograms

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  FetchMProgram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install npm packages
        run: npm install
      - name: Fetch micro program data
        run: node fetchMProgram.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: true
